version: '3'

services:
  http:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
    depends_on:
      - script

  script:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - data

  data:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: othmane
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: