version: '3'

services:
  http:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    depends_on:
      - script

  script:
    image: php:7.4-fpm
    volumes:
      - ./app:/app